config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login'     => :new
    post 'login'    => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :orders
  resources :line_items, only: [:create, :update, :destroy]
  resources :carts, only: [:show, :destroy]
  get 'store/index'
  resources :products do
    resources :reviews
  end

  get 'review_by_user' => 'reviews#review_by_user'

  root 'store#index', as: 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.sub_total_price }
  end

  def total_item
    line_items.to_a.sum { |item| item.quantity }
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def sub_total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  PAYMENT_TYPES = [ 'Check', 'Credit Card', 'Purchase Order' ]
  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES

  has_many :line_items, dependent: :destroy

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
      with: %r{\.(gift|jpg|png)\Z}i,
      message: 'must be a URL for GIFT, JPG or PNG image'
  }

  scope :search_title, -> (keyword) { where("title ILIKE ?", "%#{keyword}%")}

  def self.lastest
    Product.order(:updated_at).last
  end

  has_many :line_items, dependent: :restrict_with_error
  # before_destroy :ensure_not_referenced_by_any_line_item

  has_many :reviews, dependent: :destroy

  private

    # ensure that there are no line items referencing this product
    #def ensure_not_referenced_by_any_line_item
    #  if line_items.empty?
    #    true
    #  else
    #    errors.add(:base, 'Line Items present')
    #    false
    #  end
    #end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  REVIEW_SCORES = [1, 2, 3, 4, 5]
  validates :score, inclusion: REVIEW_SCORES
  validates :title, :content, presence: true

  scope :desc, -> { order(updated_at: :desc) }
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password

  def admin?
    return self.admin_enabled
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authorize_admin

  def index
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authorize_admin, except: [:show, :destroy]
  before_action :set_cart, only: [:show, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts/1
  def show
  end

  # DELETE /carts/1
  def destroy
    @cart.destroy
    redirect_to store_url, notice: 'Cart was successfully emptyed'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, notice: 'Invalid cart'
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @products = Product.where(nil) # creates an anonymos scope
    @products = @products.search_title(params[:search]) if params[:search]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_admin, only: [:index, :destroy]
  before_action :authorize_member, only: [:show, :edit]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.order(:name)
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    if current_user
      redirect_to users_url, notice: 'Sorry, you must log out first'
    end
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "User #{ @user.name } was successfully created"
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User #{ @user.name } was successfully updated"
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    unless @user.admin?
      @user.destroy
      redirect_to users_url, notice: 'User was successfully destroyed.'
    else
      redirect_to users_url, notice: 'Can not delete admin user.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
  def add_span_tag_around_sub_string(str)
    if params[:search].present?

      # get sub_string from string using Regex matching
      # str = 'foobar'
      # /foo/i =~ str   => 0
      # 'foo'.length   => 3
      # str.from(0).to(3-1) => 'foo'

      i = /#{params[:search]}/i =~ str
      j = params[:search].length
      str.gsub(/#{params[:search]}/i, content_tag(:span, str.from(i).to(j - 1), :class => 'found_string'))
    else
      str
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<div class="col">
  <h1>Welcome</h1>

  <p><%= link_to '- User Management', users_path %></p>
  <p><%= link_to '- Book Management', products_path %></p>
  <p><%= link_to '- Order Management', orders_path %></p>

</div>

app/views/layouts/_header.html.erb
<ul class="topnav">
  <li><%= link_to 'IT eBooks', store_path, class: 'logo' %></li>
  <li>
    <%= form_tag store_path, method: :get do %>
      <%= text_field_tag :search, params[:search], placeholder: 'Search by book title' %>
      <%= submit_tag 'Search', class: 'search_button' %>
    <% end %>
  </li>
  <ul class="topnav right">
    <li><%= link_to "Your cart ( #{ current_cart.total_item } )", cart_path(current_cart) %></li>
    <% if current_user %>
        <li><%= link_to current_user.name, current_user %></li>
        <% if current_user.admin? %>
            <li><%= link_to 'Admin', admin_path %></li>
        <% end %>
        <li><%= link_to 'Logout', logout_path, method: :delete %></li>
    <% else %>
        <li><%= link_to 'Login', login_path %></li>
        <li><%= link_to 'Register', new_user_path %></li>
    <% end %>
  </ul>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Books Online Store</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
  <div class="container">
    <div class="row col">
      <%= render 'layouts/header' %>
    </div>
    <div class="row col" id="notice"><%= notice %></div>
    <div class="row">
      <%= yield %>
    </div>
  </div>

</body>
</html>