config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login'     => :new
    post 'login'    => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :orders
  resources :line_items, only: [:create, :update, :destroy]
  resources :carts, only: [:show, :destroy]
  get 'store/index'
  resources :products do
    resources :reviews
  end

  get 'review_by_user' => 'reviews#review_by_user'

  root 'store#index', as: 'store'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password

  def admin?
    return self.admin_enabled
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_admin, only: [:index, :destroy]
  before_action :authorize_member, only: [:show, :edit]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.order(:name)
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    if current_user
      redirect_to users_url, notice: 'Sorry, you must log out first'
    end
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "User #{ @user.name } was successfully created"
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User #{ @user.name } was successfully updated"
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    unless @user.admin?
      @user.destroy
      redirect_to users_url, notice: 'User was successfully destroyed.'
    else
      redirect_to users_url, notice: 'Can not delete admin user.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> occured</h2>
        </div>
    <% end %>

  <div class="field">
    <%= f.label :name %>
    <span class="error-message"><%= @user.errors.full_messages_for(:name).to_sentence %></span>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <span class="error-message"><%= @user.errors.full_messages_for(:password).to_sentence %></span>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <span class="error-message"><%= @user.errors.full_messages_for(:password_confirmation).to_sentence %></span>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="col">
  <div class="depot_form">
    <h2>Edit user</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<div class="col">
  <h1>Listing Users</h1>

  <table class="odd_even_row">
    <thead>
      <tr>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/users/new.html.erb
<div class="col">
  <div class="depot_form">
      <h2>Register</h2>
      <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="col">
  <h2>User detail</h2>
</div>

<div class="col">
  <p>
    <strong>Name:</strong>
    <%= @user.name %>
  </p>

  <p><%= link_to 'Edit your profile', edit_user_path(@user) %></p>
  <p><%= link_to 'Your book reviews', review_by_user_path %></p>

</div>