config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login'     => :new
    post 'login'    => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :orders
  resources :line_items, only: [:create, :update, :destroy]
  resources :carts, only: [:show, :destroy]
  get 'store/index'
  resources :products do
    resources :reviews
  end

  get 'review_by_user' => 'reviews#review_by_user'

  root 'store#index', as: 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.sub_total_price }
  end

  def total_item
    line_items.to_a.sum { |item| item.quantity }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authorize_admin, except: [:show, :destroy]
  before_action :set_cart, only: [:show, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts/1
  def show
  end

  # DELETE /carts/1
  def destroy
    @cart.destroy
    redirect_to store_url, notice: 'Cart was successfully emptyed'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, notice: 'Invalid cart'
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<div class="col">
  <h2>Your cart</h2>
</div>

<div class="col">
  <table class="cell_border">
    <tr>
      <th>Book</th>
      <th>Unit price</th>
      <th>Quantity</th>
    </tr>
    <% @cart.line_items.each do |item| %>
        <tr>
          <td><%= item.product.title %></td>
          <td><%= number_to_currency(item.product.price) %></td>
          <td><%= item.quantity %></td>
        </tr>
    <% end %>
  </table>
  <p>Total: <b><%= number_to_currency(@cart.total_price) %></b></p>
  <%= button_to 'Check Out', new_order_path, method: :get, class: 'check_out click' %>
  <%= button_to 'Empty cart', @cart, method: :delete, data: { confirm: 'Are you sure?' }, class: 'empty_cart click' %><br>
  <hr>
  <%= link_to 'Continue shopping >>>', store_path %>
</div>