config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login'     => :new
    post 'login'    => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :orders
  resources :line_items, only: [:create, :update, :destroy]
  resources :carts, only: [:show, :destroy]
  get 'store/index'
  resources :products do
    resources :reviews
  end

  get 'review_by_user' => 'reviews#review_by_user'

  root 'store#index', as: 'store'

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
      with: %r{\.(gift|jpg|png)\Z}i,
      message: 'must be a URL for GIFT, JPG or PNG image'
  }

  scope :search_title, -> (keyword) { where("title ILIKE ?", "%#{keyword}%")}

  def self.lastest
    Product.order(:updated_at).last
  end

  has_many :line_items, dependent: :restrict_with_error
  # before_destroy :ensure_not_referenced_by_any_line_item

  has_many :reviews, dependent: :destroy

  private

    # ensure that there are no line items referencing this product
    #def ensure_not_referenced_by_any_line_item
    #  if line_items.empty?
    #    true
    #  else
    #    errors.add(:base, 'Line Items present')
    #    false
    #  end
    #end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authorize_admin, except: [:show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    if @product.destroy
      redirect_to products_url, notice: 'Product was successfully destroyed.'
    else
      redirect_to products_url, notice: 'Product can not be deleted if it is still in cart'
      #redirect_to products_url, notice: "#{@product.errors.full_messages.first}"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
    <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> occured</h2>
        </div>
    <% end %>

  <div class="field">
    <%= f.label :title %>
    <span class="error-message"><%= @product.errors.full_messages_for(:title).to_sentence %></span>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <span class="error-message"><%= @product.errors.full_messages_for(:description).to_sentence %></span>
    <%= f.text_area(:description, rows: 15) %>
  </div>
  <div class="field">
    <%= f.label :image_url %>
    <span class="error-message"><%= @product.errors.full_messages_for(:image_url).to_sentence %></span>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <span class="error-message"><%= @product.errors.full_messages_for(:price).to_sentence %></span>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit ( f.object.new_record? ? 'Create Book' : 'Update Book' )%>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="col">
  <div class="depot_form">
    <h2>Edit book</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/products/index.html.erb
<div class="col">
  <h1>Listing Books</h1>

  <p><%= link_to 'New Book [+]', new_product_path %></p>

  <table class="odd_even_row">
    <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @products.each do |product| %>
        <tr>
          <td><%= product.title %></td>
          <td><%= link_to 'Show', product %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

</div>

app/views/products/new.html.erb
<div class="col">
  <div class="depot_form">
    <h2>Create new book</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/products/show.html.erb
<div class="col book_title">
  <h2><%= @product.title %></h2>
</div>

<div class="col book_detail">
  <div class="row">
    <div class="col book_image">
      <%= image_tag(@product.image_url) %>
    </div>
    <div class="col book_description">
      <p><%= @product.description %></p>
      <table class="odd_even_row">
        <tr>
          <td>Price</td>
          <td><%= number_to_currency(@product.price) %></td>
        </tr>
        <tr>
          <td>Publisher</td>
          <td>Willey</td>
        </tr>
        <tr>
          <td>Author</td>
          <td>Pawel Cichosz</td>
        </tr>
        <tr>
          <td>ISBN</td>
          <td>97811183332580</td>
        </tr>
        <tr>
          <td>Pages</td>
          <td>720</td>
        </tr>
        <tr>
          <td>Year</td>
          <td>2015</td>
        </tr>
        <tr>
          <td>Language</td>
          <td>English</td>
        </tr>
        <tr>
          <td>File size</td>
          <td>8.5 MB</td>
        </tr>
        <tr>
          <td>File Type</td>
          <td>PDF</td>
        </tr>
        <tr>
          <td><%= link_to 'Download', "#", class: 'download' %></td>
          <td><%= button_to 'Add to Cart', line_items_path(product_id: @product), class: 'click' %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

<div class="col">
  <p><%= link_to 'Review this book', new_product_review_path(@product), class: 'review' %></p>
</div>

<div class="col review_list">
  <h2>Customer Reviews</h2>
  <%= render 'reviews/index', product: @product %>
</div>